version: "3.2"

services:
  wordpress:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wp-content/:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    env_file:
      - ./.env

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    env_file:
      - ./.env
